export const UserInvalid = 'UserInvalidError'
export const UserPermissionDenied = 'UserPermissionError'
export const RefreshTokenExpired = 'RefreshTokenExpired'
export const RefreshTokenRequired = 'RefreshTokenRequired'
export const EmailAddrValidationError = 'EmailAddrValidationError'
export const EmailSendFailed = 'EmailSendFailed'
